name: TerminalImageViewer CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -qy imagemagick
    - name: Build
      run: make -C src
    - name: Install
      run: sudo make -C src install
    - name: Test
      run: tiv -w 80 -h 24 -2 /usr/share/pixmaps/debian-logo.png
