name: Build and run

on:
  push:
    branches: [ "master", "github-actions-image-test" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install -qy imagemagick
    - name: Validate gcc version
      run: |
        if [[ $(gcc --version | awk '/gcc/ && ($3+0)>13{print "gcc-13+"}') != "gcc-13+" ]]; then
          # Script courtesy of https://stackoverflow.com/a/67791068/16134571
          sudo apt install gcc-13 g++-13
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 --slave /usr/bin/g++ g++ /usr/bin/g++-13 --slave /usr/bin/gcov gcov /usr/bin/gcov-13
          sudo update-alternatives --set gcc /usr/bin/gcc-13
        fi
    - name: Build
      run: make -C src
    - name: Test
      run: ./src/tiv -w 80 -h 24 -d /opt/microsoft/msedge/product_logo_128.png /opt/google/chrome/product_logo_128.png /home/runner/.nvm/.github/external-threat-actor.png /home/runner/.nvm/.github/insider-threat-actor-and-libs.png /home/linuxbrew/.linuxbrew/Homebrew/package/resources/Homebrew.png /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test/support/fixtures/test.png /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test/support/fixtures/test.jpg /home/linuxbrew/.linuxbrew/Homebrew/docs/assets/img/docs/ /usr/local/share/icons/hicolor/128x128/apps/CMakeSetup.png /usr/local/doc/cmake/html/_static/ /usr/local/lib/android/sdk/extras/google/google_play_services/samples/tagmanager/cuteanimals/res/drawable/ /usr/local/lib/android/sdk/extras/google/google_play_services/samples/wallet/res/drawable-hdpi/ /usr/local/lib/node_modules/netlify-cli/node_modules/fastify/node_modules/pino/ /usr/share/plymouth/themes/spinner/watermark.png /usr/share/R/doc/manual/images/ /usr/share/miniconda/share/doc/xz/api/ /usr/share/pixmaps/ /usr/share/apache2/icons/apache_pb.png /usr/share/swift/usr/share/docc/render/developer-og-twitter.jpg /usr/share/doc/libpng-dev/examples/pngtest.png
